#!/bin/bash

cat <<'EOFa' > /usr/sbin/dnstt.sh
#!/bin/bash
/etc/slowdns/./restartdns
EOFa
chmod +x /usr/sbin/dnstt.sh

cat <<'EOFOne' > /etc/systemd/system/dnstt.service
[Unit]
Description=sshws service
Documentation=https://google.com
After=network.target nss-lookup.target
[Service]
Type=simple
User=root
NoNewPrivileges=true
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
WorkingDirectory=/usr/sbin
ExecStart=/bin/bash /usr/sbin/dnstt.sh
ProtectSystem=true
ProtectHome=true
RemainAfterExit=yes
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOFOne
